### ISSUE TITLE
issues introduced with 51cf70bdf8445e1d46d81f2a9d7c9b4aab113c99

### ISSUE THREAD

**Issue by looooo** [booya-at/OpenGlider#36]
- some widgets get added twice
![bildschirmfoto von 2018-12-05 13-32-30](https://user-images.githubusercontent.com/5084704/49513794-6e0c1780-f892-11e8-9546-36e64f12b74e.png)

**Comment by looooo** [comment]
- widget not shown at all
![bildschirmfoto von 2018-12-05 13-35-24](https://user-images.githubusercontent.com/5084704/49513893-b4fa0d00-f892-11e8-9cd1-2d58d7148880.png)

**Comment by looooo** [comment]
- missing file:
```
======================================================================
ERROR: test_export_plots (test_glider_exports.TestGlider)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/booya-at/OpenGlider/tests/test_glider_exports.py", line 80, in test_export_plots
    all.export_dxf(dxfile)
  File "/home/travis/build/booya-at/OpenGlider/openglider/plots/drawing/layout.py", line 496, in export_dxf
    drawing = ezdxf.new(dxfversion=dxfversion)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/ezdxf/filemanagement.py", line 32, in new
    dwg = Drawing.new(dxfversion)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/ezdxf/drawing.py", line 353, in new
    stream = finder.getstream(dxfversion.upper())
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/ezdxf/templates/__init__.py", line 35, in getstream
    return io.open(self.filepath(dxfversion), encoding='cp1252')
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/ezdxf/templates/AC1015.dxf'
```

**Comment by looooo** [comment]
seems to be an issue with ezdxf.
