### ISSUE TITLE
Problem creating new glider in workbench.

### ISSUE THREAD

**Issue by gerrie-myburgh** [booya-at/OpenGlider#63]
11:51:44  Running the Python command 'CreateGlider' failed:
Traceback (most recent call last):
  File "/home/gerrie/.local/lib/python3.8/site-packages/freecad/freecad_glider/tools/__init__.py", line 142, in Activated
    CreateGlider.create_glider()
  File "/home/gerrie/.local/lib/python3.8/site-packages/freecad/freecad_glider/tools/__init__.py", line 132, in create_glider
    vp.updateData()
  File "/home/gerrie/.local/lib/python3.8/site-packages/freecad/freecad_glider/tools/glider.py", line 415, in updateData
    self._updateData(self.view_obj, prop)
  File "/home/gerrie/.local/lib/python3.8/site-packages/freecad/freecad_glider/tools/glider.py", line 456, in _updateData
    self.update_glider(midribs=fp.num_ribs,
  File "/home/gerrie/.local/lib/python3.8/site-packages/freecad/freecad_glider/tools/glider.py", line 474, in update_glider
    draw_glider(self.glider, vis_glider=self.vis_glider, midribs=midribs, 
  File "/home/gerrie/.local/lib/python3.8/site-packages/freecad/freecad_glider/tools/glider.py", line 588, in draw_glider
    msh += diagonal.get_mesh(cell, insert_points=4)
  File "/home/gerrie/.local/lib/python3.8/site-packages/openglider/glider/cell/elements.py", line 155, in get_mesh
    line_points.append(left[x_pos * (num_left - 1)] * (1. - y_pos) +

**'openglider_cpp.euklid.PolyLine3D' object is not subscriptable**

**configuration** is
OS: Ubuntu 20.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Branch: unknown
Hash: 0d9536ed3e8c7f40197b5606e1b7873625e1d6fe
Python version: 3.8.10
Qt version: 5.12.8
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United Kingdom (en_GB)

**Comment by gerrie-myburgh** [comment]
Rresolved - installed the pligin incorrectly
