### ISSUE TITLE
No module named 'numpy.lib.function_base'

### ISSUE THREAD

**Issue by zdavatz** [booya-at/OpenGlider#78]
1. I installed using `conda`
2. Currently I am getting this error, when starting `freecad` from commandline, Start > Glider
3.  <img width="931" alt="Bildschirmfoto 2024-09-26 um 11 27 21" src="https://github.com/user-attachments/assets/8482e8b4-6b1e-4781-ac0e-01e7bf7d1531">
4. This happens on Mac and on Linux.
```
No module named 'numpy.lib.function_base'
Traceback (most recent call last):
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/freecad/freecad_glider/init_gui.py", line 67, in Initialize
    from . import tools
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/freecad/freecad_glider/tools/__init__.py", line 5, in <module>
    import openglider
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/openglider/__init__.py", line 28, in <module>
    import openglider.glider
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/openglider/glider/__init__.py", line 1, in <module>
    from openglider.glider import cell
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/openglider/glider/cell/__init__.py", line 2, in <module>
    from openglider.glider.cell.cell import Cell
  File "/Users/zdavatz/miniconda3/envs/openglider/lib/python3.11/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    ret
```
5. Numpy seems to be installed:
6. ```
(openglider) ➜  ~ pip3.11 install numpy
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (2.1.1)
```

**Comment by zdavatz** [comment]
Do not mix the Github and Conda installs.
