### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'src/version.hpp'

### ISSUE THREAD

**Issue by haozhiyu** [booya-at/OpenGlider#81]
I installed it on my Mac, and it shows another error: error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/78/qyjwnfvj4cjc2l4wpt3156640000gs/T/pip-build-env-hza7fowt/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/78/qyjwnfvj4cjc2l4wpt3156640000gs/T/pip-build-env-hza7fowt/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/78/qyjwnfvj4cjc2l4wpt3156640000gs/T/pip-build-env-hza7fowt/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/78/qyjwnfvj4cjc2l4wpt3156640000gs/T/pip-build-env-hza7fowt/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 85, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'src/version.hpp'
      [end of output]

**Comment by GeorgEngineering** [comment]
I receive this error as well. I've tried installing two separate times, once using conda, and another using pip. Each time, I receive this error. In addition to this error message, when I try installing with pip, I see this message at the bottom: 

ERROR: Failed to build 'pyfoil' when getting requirements to build wheel
